version: '3'

name: nighty_night_web_app
networks:
  nighty_night_network:
    driver: bridge
volumes:
  postgres:
    driver: local
  redis:
    driver: local
services:
  postgres:
    image: postgres:14.9
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
          - postgres:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ../migrations/2023-05-25-174758_create_tables/up.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - nighty_night_network
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --loglevel warning
    volumes: 
      - redis:/data
    networks:
      - nighty_night_network
  backend:
    image: 'nighty_night:latest'
    ports:
      - '${PORT}:${PORT}'
    environment:
      - BRANCH
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - LOGGER_LEVEL
      - ADDRESS
      - PORT
      - REDIS_ADDRESS
      - REDIS_PORT
      - SESSION_DURATION
    networks:
      - nighty_night_network
    depends_on:
      - postgres
      - redis
