apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    group: nighty.night.db
    app: PostgreSQL
    branch: minikube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi