apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-deployment
  labels:
    group: nighty.night.db
    app: PostgreSQL
    branch: minikube
spec:
  selector:
    matchLabels:
      app: PostgreSQL
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: PostgreSQL
    spec:
      containers:
        - image: postgres:latest
          name: psql-db
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: nighty-night-config-map
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nighty-night-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nighty-night-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: psql-persistent-storage
              mountPath: /var/lib/postgres
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: psql-persistent-storage
          persistentVolumeClaim:
            claimName: psql-pv-claim
        - name: initdb
          configMap:
            name: psql-config-map