apiVersion: v1
kind: Service
metadata:
  name: nighty-night-service
  labels:
    group: nighty.night.app
    app: nighty-night
    branch: minikube
spec:
  selector:
    app: nighty-night
  ports:
  - port: 3000
    name: service-port
    protocol: TCP
    targetPort: 3000